{% set name = "NaMaster" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LSSTDESC/NaMaster/archive/v{{ version }}.tar.gz
  sha256: 4f3ce3037c6473d47b30fd63b7187347011b98dc2d37d5910b4b5bc32130bb60

build:
  number: 1
  skip: true  # [win or (python_impl == 'pypy') or py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]    
    - make
    - autoconf
    - automake
    - wget
    - gnuconfig  # [unix]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - libtool
  host:
    - python
    - pip
    - gsl
    - fftw
    - cfitsio
    - chealpix
    - numpy
    - libblas
    - libcblas
    - liblapack
  run:
    - python
    - gsl
    - fftw
    - chealpix
    - numpy
    - ducc0
    - healpy

test:
  imports:
    - pymaster
  requires:
    - pytest
  source_files:
    - pymaster/tests/*
    - test/*
  commands:
    - pytest -vv pymaster/tests

about:
  home: https://github.com/LSSTDESC/NaMaster
  license: BSD-3-Clause AND GPL-2.0-only
  license_family: BSD
  license_file:
    - LICENSE
    - COPYING
  summary: pseudo-Cl power spectra w/ masking for spin-0 and spin-2 fields
  description: |
    NaMaster is a C library, Python module and standalone program to compute
    full-sky angular cross-power spectra of masked, spin-0 and spin-2 fields
    with an arbitrary number of known contaminants using a pseudo-Cl
    (aka MASTER) approach. The code also implements E/B-mode purification
    and is available in both full-sky and flat-sky modes.
  doc_url: https://namaster.readthedocs.io

extra:
  recipe-maintainers:
    - beckermr
    - damonge
