appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: h1dxooCxfDLh+wI3dKtPCfAIs+Y3wNOc+okkJO9I9WcOhCaGfBzJyFC3fJmTr65axB/1+cLYx/id+e7PjY3QI1M2qi7NhCYmUN8Etr0yblFVOnjlR8EtAuT9yY0JLppd7g46hO/axIhO9S63NDJYHxkF8j9tUX5rlSosQT0VDIRfUeGiqK1uzCqHOqtp2fplP5laE+0qs5PTR0ZJWz0LKfS9UuQalwCEZOIm9PmK5UKIVu3bz1S5BdrMnynaatxvJCwz7ynMRHa9TfaYshLLTiLmZT+dt5meNUAKqwakKzV/QjzvsEx9GwhIJPRauo1oud3Vvf2gysOxb9YZfBn6fEA5U4JOmuwva68iN5bfOPnBxJLTL6lXZBANwV1GhSqSdP+NYxjTYMjLkiup7VcS7F6HQGcdqrBfvfyQb80IYd96QTH1VNLWqMM9HE6YMYzanwT3/aXgMFiNzmP7oKwzYh+MA4Jd3iBi8iyuUZ+COt8ooHDXTypw/BMarEZXeMhZOLG0WFmFp3kw3E27dxEg5EPalmQ2/YDyJimfi8pom9g+qIZgRn9+F9wU6SgOHqf7FAyy6loxoIAO8N+a6gwBem89CEkUgsI/vdLBb/SIT1WbwsbS/oZ2SPSmebAZGXjv8ONRghBLhGnV11SSCrAZ55ZeubsGBFCtaTJxyemP03U=}
bot:
  automerge: true
conda_forge_output_validation: true
